name: GitHub Actions Demo
on:
  push:
    branches:
      - develop-compose
jobs:
  commit-message-parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          
      - name: Check commit message
        id: check_commit
        run: |
          if [[ "${{ steps.get_commit_message.outputs.commit_message }}" == *"[QA]"* ]]; then
            echo "Commit message contains '[QA]'. Triggering Firebase upload..."
            echo "should_upload=true" >> $GITHUB_OUTPUT
          else
            echo "Commit message does not contain '[QA]'. No action triggered."
            echo "should_upload=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Qa commit message parse
        if: steps.check_commit.outputs.should_upload == 'true'
        run: |
          echo "You can upload the app from Firebase App Distribution"